#Update ubuntu
FROM python:3.8.9-slim

# =========
# TIME_ZONE
# =========
ENV TZ=US
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# ==========
# PACKAGE
# ==========
RUN apt-get update && apt-get install -y
RUN apt-get install -y software-properties-common
RUN apt-get install -y curl nano wget procps iputils-ping
RUN apt-get install -y libreadline-gplv2-dev libncursesw5-dev libssl-dev \
                        libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev \
                        xvfb libjpeg-dev zlib1g-dev python-setuptools
RUN pip3 install --upgrade pip

# ==========
# EXTRA PACKAGE
# ==========
RUN apt install -y gcc g++

RUN mkdir -p /app
ENV APP_PATH /app
WORKDIR $APP_PATH

# ====================
# INSTALL REQUIREMENTS
# ====================
COPY ./requirements.txt $APP_PATH/requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt

COPY . $APP_PATH
# ==========
# RUN SCRIPT
# ==========
COPY start.sh $APP_PATH
RUN chmod a+x $APP_PATH/start.sh
ENTRYPOINT ["/app/start.sh"]