#Update ubuntu
FROM python:3.8.9-slim

# =========
# TIME_ZONE
# =========
ENV TZ=US
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# ==========
# PACKAGE
# ==========
RUN apt-get update && apt-get install -y
RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get install -y zlib1g-dev curl nano nodejs npm
RUN apt-get install -y libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev xvfb
RUN pip3 install --upgrade pip
RUN apt-get update && apt-get install -y
RUN apt-get -qq install -y gcc crudini python python-dev libffi-dev python-virtualenv python-setuptools libjpeg-dev zlib1g-dev

ENV APP_PATH /app
WORKDIR $APP_PATH

COPY tool $APP_PATH/tool
# ====================
# INSTALL REQUIREMENTS
# ====================
COPY ./requirements.txt $APP_PATH/requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt

# ==========
# RUN SCRIPT
# ==========
COPY start.sh $APP_PATH
RUN chmod a+x $APP_PATH/start.sh
ENTRYPOINT ["/home/start.sh"]