# Generated by Django 2.2.5 on 2021-05-07 07:13

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
            ],
            options={
                'db_table': 'contest',
            },
        ),
        migrations.CreateModel(
            name='HtmlDocument',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('html_content', models.TextField()),
            ],
            options={
                'db_table': 'html_document',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('path', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.FileField(upload_to='contest/<django.db.models.fields.related.ForeignKey>')),
                ('score', models.FloatField()),
                ('code_test', models.FileField(upload_to='contest/<django.db.models.fields.related.ForeignKey>')),
                ('data_sample', models.FileField(upload_to='contest/<django.db.models.fields.related.ForeignKey>')),
                ('train_data', models.FileField(upload_to='contest/<django.db.models.fields.related.ForeignKey>')),
                ('test_data', models.FileField(upload_to='contest/<django.db.models.fields.related.ForeignKey>')),
                ('time_executed_limit', models.FloatField()),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_id', to='api.Contest')),
                ('languages', djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Language')),
            ],
            options={
                'db_table': 'problem',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('first_name', models.TextField(default='', max_length=50)),
                ('last_name', models.TextField(default='', max_length=50)),
                ('password', models.TextField()),
                ('role', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_organizer', models.BooleanField(default=False)),
                ('url', models.URLField()),
                ('attended_contest', models.ManyToManyField(blank=True, to='api.Contest')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('model_file', models.FileField(upload_to='result/')),
                ('code_test', models.FileField(upload_to='result/')),
                ('code_train', models.FileField(upload_to='result/')),
                ('accuracy', models.FloatField()),
                ('time_submit', models.DateTimeField(auto_now_add=True)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Language')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Problem')),
            ],
            options={
                'db_table': 'result',
            },
        ),
        migrations.AddField(
            model_name='contest',
            name='contestants',
            field=models.ManyToManyField(related_name='contestants', to='api.User'),
        ),
        migrations.AddField(
            model_name='contest',
            name='created_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_user', to='api.User'),
        ),
    ]
