# Generated by Django 2.2.5 on 2021-05-02 10:39

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_basic_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='HtmlDocument',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('html_content', models.TextField()),
            ],
            options={
                'db_table': 'html_document',
            },
        ),
    ]
