# Generated by Django 2.2.5 on 2021-05-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_htmldocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='constestants',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='language',
        ),
        migrations.AddField(
            model_name='contest',
            name='contestants',
            field=models.ManyToManyField(related_name='contestants', to='api.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='attended_contest',
            field=models.ManyToManyField(related_name='attended_contest', to='api.Contest'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='code_test',
            field=models.FileField(upload_to='code_test/<bound method Field.__str__ of <django.db.models.fields.related.ForeignKey>>'),
        ),
    ]
