# Generated by Django 2.2.5 on 2021-05-16 06:18

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210516_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='code_test',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media/result'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='result',
            name='code_train',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media/result'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='result',
            name='model_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media/result'), upload_to=''),
        ),
    ]
