# Generated by Django 2.2.5 on 2021-05-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210503_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='attended_contest',
            field=models.ManyToManyField(blank=True, to='api.Contest'),
        ),
    ]
