# Generated by Django 2.2.5 on 2021-06-06 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210516_1318'),
        ('api', '0002_auto_20210516_1033'),
    ]

    operations = [
    ]
