# Generated by Django 2.2.5 on 2021-06-06 21:19

import api.models.Result
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20210606_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='contestants',
        ),
        migrations.RemoveField(
            model_name='user',
            name='attended_contest',
        ),
        migrations.AddField(
            model_name='contest',
            name='attended_contestants',
            field=djongo.models.fields.ArrayReferenceField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.User'),
        ),
        migrations.AddField(
            model_name='language',
            name='file_extensions',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='description_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='status',
            field=models.TextField(default='N'),
        ),
        migrations.AddField(
            model_name='result',
            name='time_excute',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='attended_contests',
            field=djongo.models.fields.ArrayReferenceField(default=[], on_delete=django.db.models.deletion.CASCADE, to='api.Contest'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='code_test',
            field=models.FileField(upload_to='contest/'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='data_sample',
            field=models.FileField(upload_to='contest/'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.FileField(upload_to='contest/'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='test_data',
            field=models.FileField(upload_to='contest/'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='train_data',
            field=models.FileField(upload_to='contest/'),
        ),
        migrations.AlterField(
            model_name='result',
            name='code_test',
            field=models.FileField(upload_to=api.models.Result.get_result_directory_path),
        ),
        migrations.AlterField(
            model_name='result',
            name='code_train',
            field=models.FileField(upload_to=api.models.Result.get_result_directory_path),
        ),
        migrations.AlterField(
            model_name='result',
            name='model_file',
            field=models.FileField(upload_to=api.models.Result.get_result_directory_path),
        ),
    ]
