# Generated by Django 2.2.5 on 2021-07-30 07:00

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210607_0419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('total_score', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'contestant',
            },
        ),
        migrations.AlterField(
            model_name='contest',
            name='attended_contestants',
            field=djongo.models.fields.ArrayReferenceField(default=[], on_delete=djongo.models.fields.ArrayReferenceField._on_delete, related_name='attended_contestants', to='api.Contestant'),
        ),
        migrations.AlterField(
            model_name='user',
            name='attended_contests',
            field=djongo.models.fields.ArrayReferenceField(default=[], on_delete=django.db.models.deletion.CASCADE, related_name='attended_contests', to='api.Contestant'),
        ),
        migrations.AddField(
            model_name='contestant',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestant_contest_id', to='api.Contest'),
        ),
        migrations.AddField(
            model_name='contestant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestant_user', to='api.User'),
        ),
    ]
