# Generated by Django 2.2.5 on 2021-08-08 05:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210730_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contestant',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
