# Generated by Django 2.2.5 on 2021-08-10 09:49

from django.db import migrations
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210808_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='time_excute',
            new_name='time_execute',
        ),
        migrations.AlterField(
            model_name='user',
            name='attended_contests',
            field=djongo.models.fields.ArrayReferenceField(default=[], on_delete=django.db.models.deletion.DO_NOTHING, related_name='attended_contests', to='api.Contestant'),
        ),
    ]
